include_directories(Selectors)
file(GLOB CPP_FILES_Selectors Selectors/*.cpp)
file(GLOB INL_FILES_Selectors Selectors/*.inl)
file(GLOB H_FILES_Selectors Selectors/*.h)
source_group("Selectors"        FILES ${CPP_FILES_Selectors} ${INL_FILES_Selectors} ${H_FILES_Selectors})
set(CPP_FILES ${CPP_FILES} ${CPP_FILES_Selectors})
set(INL_FILES ${INL_FILES} ${INL_FILES_Selectors})
set(H_FILES ${H_FILES} ${H_FILES_Selectors})