include_directories(General)
file(GLOB CPP_FILES_General General/*.cpp)
file(GLOB INL_FILES_General General/*.inl)
file(GLOB H_FILES_General General/*.h)
source_group("General"        FILES ${CPP_FILES_General} ${INL_FILES_General} ${H_FILES_General})
set(CPP_FILES ${CPP_FILES} ${CPP_FILES_General})
set(INL_FILES ${INL_FILES} ${INL_FILES_General})
set(H_FILES ${H_FILES} ${H_FILES_General})