message(STATUS "Loading clang-cl using ninja toolchain!")
find_program(CLANG_CL clang-cl HINTS "$ENV{PROGRAMFILES}/LLVM/bin")
if(NOT CLANG_CL)
    message(FATAL_ERROR "Unable to find clang-cl")
else()
    get_filename_component(LLVM_BIN_DIR "${CLANG_CL}" DIRECTORY CACHE)
    message(STATUS "Found clang-cl in ${LLVM_BIN_DIR}")
    list(APPEND CMAKE_PROGRAM_PATH "${LLVM_BIN_DIR}")
endif()
set(CMAKE_C_COMPILER "${LLVM_BIN_DIR}/clang-cl.exe")
set(CMAKE_CXX_COMPILER "${LLVM_BIN_DIR}/clang-cl.exe")
set(CMAKE_LINKER "${LLVM_BIN_DIR}/lld-link.exe")
set(CMAKE_AR "${LLVM_BIN_DIR}/llvm-lib.exe")
set(CMAKE_RANLIB)
set(CMAKE_RC_COMPILER "${LLVM_BIN_DIR}/llvm-rc.exe")
set(CMAKE_NM "${LLVM_BIN_DIR}/llvm-nm.exe")

include("${CMAKE_CURRENT_LIST_DIR}/toolchain_msvc_general.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/toolchain_vs_llvm.cmake")

