include_directories(Simulator)
file(GLOB CPP_FILES_Simulator Simulator/*.cpp)
file(GLOB INL_FILES_Simulator Simulator/*.inl)
file(GLOB H_FILES_Simulator Simulator/*.h)
source_group("Simulator"        FILES ${CPP_FILES_Simulator} ${INL_FILES_Simulator} ${H_FILES_Simulator})
set(CPP_FILES ${CPP_FILES} ${CPP_FILES_Simulator})
set(INL_FILES ${INL_FILES} ${INL_FILES_Simulator})
set(H_FILES ${H_FILES} ${H_FILES_Simulator})